const { getDefaultConfig } = require('expo/metro-config');

const config = getDefaultConfig(__dirname);

// Let Metro bundle the .sql migration files generated by drizzle-kit,
// and the .wasm binary expo-sqlite's web build depends on.
config.resolver.assetExts.push('sql', 'wasm');

module.exports = config;
